[package]
name = "client"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
memex-shared = { path = "../memex-shared" }
anyhow.workspace = true
automerge.workspace = true
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
wasm-bindgen = "0.2.121"
getrandom = { version = "0.4.2", features = ['wasm_js'] }
log = "0.4.29"
js-sys = "0.3.99"
leptos = { version = "0.8.19", features = ["csr"] }
wasm-bindgen-futures = "0.4.72"
indexed_db_futures = { version = "0.6.4", features = ["typed-arrays"] }
futures = "0.3.32"
tracing = "0.1.44"

[dependencies.web-sys]
version = "0.3.98"
features = [
  'BinaryType',
  'Blob',
  'CanvasRenderingContext2d',
  'console',
  'Document',
  'DomRect',
  'Element',
  'HtmlCanvasElement',
  'HtmlInputElement',
  'HtmlOptionElement',
  'HtmlSelectElement',
  'KeyboardEvent',
  'MessageEvent',
  'MouseEvent',
  'PointerEvent',
  'Storage',
  'Touch',
  'TouchEvent',
  'TouchList',
  'WebSocket',
  'Window',
]
