default: (wasm "dev") parcel-dev serve

[working-directory: 'dist']
serve:
    pnpm dlx http-server

wasm profile:
    wasm-pack build --target web --out-dir {{wasm_dir}} --no-typescript --{{profile}} --no-pack

parcel-dev:
    pnpm parcel build public/index.html

parcel-release:
    pnpm parcel build public/index.html --public-url /memex/

websocket path='':
    sed -e 's_"ws://localhost:3036/ws"_"{{path}}"_' dist/public*.js -i

test:
    wasm-pack test --chrome

clean:
    rm -rf dist

clean-all: clean
    rm -rf {{wasm_dir}}
    rm -rf .parcel-cache

# allow preview before deploy
release: clean-all (wasm "release") parcel-release (websocket "wss://austenite.moray-palermo.ts.net/memex/api/ws")

wasm_dir := ".wasm_pack"
