default: (wasm "dev") parcel serve

[working-directory: 'dist']
serve:
    pnpm dlx http-server

wasm profile:
    wasm-pack build --target web --out-dir {{wasm_dir}} --no-typescript --{{profile}} --no-pack

parcel:
    pnpm parcel build public/index.html --public-url /memex/

install path:
    cp -r dist {{path}}

websocket path='':
    sed -e 's_"ws://localhost:3036/ws"_"{{path}}"_' public/main.js > public/copy.js
    mv public/copy.js public/main.js

test:
    wasm-pack test --chrome

clean:
    rm -rf dist

clean-all: clean
    rm -rf {{wasm_dir}}
    rm -rf .parcel-cache

# allow preview before deploy
release: clean-all (wasm "release") (websocket "wss://austenite.moray-palermo.ts.net/memex/api/ws") parcel

wasm_dir := ".wasm_pack"
