[package]
name = "memex"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
askama = "0.12.1"
axum = "0.7.9"
clap = { version = "4.0.29", features = ["derive"] }
# diesel = "2.2.6"
futures-util = "0.3.31"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "sqlite"] }
# sqlx-sqlite = "0.8.3"
tokio = { version = "1.42.0", features = [ "rt-multi-thread" ] }
winnow = "0.6.22"