[package]
name = "server"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
memex-shared = { path = "../memex-shared" }
anyhow.workspace = true
automerge.workspace = true
axum = { version = "0.8.9", features = ["ws"] }
axum-macros = "0.5.1"
ciborium.workspace = true
lazy_static = "1.5.0"
openssl = { version = "0.10", features = ["vendored"] }
prometheus = "0.14.0"
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls", "bigdecimal", "uuid", "time", "migrate", "macros"] }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt", "json"] }
tracing.workspace = true
uuid.workspace = true
webauthn-rs = { path = "../../../build/webauthn-rs/webauthn-rs/", features = ["danger-allow-state-serialisation"] }
webauthn-rs-core = { path = "../../../build/webauthn-rs/webauthn-rs-core/" }
