[package]
name = "memex-shared"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
automerge.workspace = true
base64 = "0.23.1"
ciborium.workspace = true
getrandom.workspace = true
log = "0.4.30"
serde = "1.0.229"
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
proptest = "1.11.0"
